apiVersion: v1
kind: Endpoints
metadata:
  namespace: rangine-demo
  name: external-service-demo
subsets:
  - addresses:
      - ip: "192.168.1.4"
    ports:
      - name:  tcp-8003-80
        port: 99