apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
#该类型role属于集群级别,因此不指定namespace
  labels:
    rangine-demo/rbac-generated: "true"
  name: rangine-demo:cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'