apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rangine-demo
  name: titrxw-rangine-demo-pods-dev-bind
subjects:
- kind: User
  name: titrxw:pod  #创建好的用户名
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: rangine-demo:pods-dev
  apiGroup: rbac.authorization.k8s.io