apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: rangine-demo
  name: extrenal-service
  labels:
    name: external-service
spec:
  rules:
  - host: external.titrxw.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: external-service-demo
            port: 
              number: 8003
